### ISSUE TITLE
Crear módulo de facturacion

### ISSUE THREAD

**Issue by DVazquez55** [GhostX94/ERP-Quezla-Master#2]
Generar modulo de facturacion

-desde modulo de ventas crear formulario para generar las facturas

-En la primer ventana se mostrara la lista de las facturas generadas de la sucursal activa (la que inicio sesion) como la ventana de  las ventas de mostrador

-en esta primer ventana habra un boton que abrira una nueva ventana donde se ingresaran los datos para la facturacion

-En esta ventana habra un control que agregara "n" tickets a la factura, puede o no haber tickets agregados para la factura, esto llevara a que se pueda generar una factura sin necesidad de hacer una venta de mostrador (esto servira para vender a las empresas que son de servicios)

-Esta nueva ventana tendra los campos de la facturacion como uso de cfdi, metodos de pago (en caso de no tener tickets), moneda, etc (incluir todos los datos necesarios para la generacion)

-impresion de formato de factura y timbrado

NOTA: en la ventana donde se encontraran los datos de facturacion se agregaran un checkbox que dira "FACTURACION GLOBAL", un combobox con las opciones de efectivo,trasnferencia,trajeta de debito y tarjeta de credito, un campo de fecha y un textbox para indiciar el porcentaje de lo que se facturara y un boton para consultar las ventas con los datos especificados en los controles antes mencionados (se enlaza automaticamente los tickets que fueron resultado de la consulta, emulando el funcionamiento del control que agrega los tickets descrito anteriormente ), con el resultado de la consulta se generara el calculo segun el porcentaje dado (mostrar los resultados del calculo, subtotal,iva y total) y se procedera a indicar los demas datos necesarios para la facturacion (NO SE PUEDE GENERAR UNA FACTURA GLOBAL EN EL QUE LA FECHA SEA MAYOR A UN DIA ATRAS QUE EL DIA ACTUAL).

Cuando no se indique el checkbox de factura global y se realice una factura sin tickets (registros de ventas mostrador) se generara automaticamente un registro en ventas mostrador antes de la generacion de la factura para despues enlazar dicha venta con la factura, todo esto es con el fin de llevar el control correcto de las ventas y que no se dupliquen datos para cuando se generen los reportes de las ventas.

**Comment by GhostX94** [comment]
Productos   -> IdProductoHash
Clientes -> IdClienteHash
Ventas_Mostrador -> FacturaHash

---------
Quezla

Token by Client
afectando tabla empresa
