### ISSUE TITLE
Monedero electronico

### ISSUE THREAD

**Issue by DVazquez55** [GhostX94/ERP-Quezla-Master#21]
Monedero electrónico:

Paso 1(venta) : cuando un articulo tiene monedero electrónico, aparece el porcentaje en un campo llamado "MONEDERO", al cargar los datos de los artículos en el formulario de ventas mostrador se puede hacer el cálculo de Dicho porcentaje para sacar la parte proporcional en cantidad de dinero o al recorrer los artículos al dar click en el botón (guardar), la suma de las cantidades de monedero serán asignadas a la cuenta del cliente(tabla monedero) si no hay registro en la tabla agregarlo
 Si la cuenta no tiene asignada una tarjeta(poner campo de tarjeta en la tabla de monedero, dicho campo tendrá el  código de la tarjeta) mostrar en pantalla una ventana para asignar el código de tarjeta  y se guarda
Pasado esto se finaliza la venta
 Paso 2(compra): cuando el cliente compra o paga con monedero electrónico antes de guardar la venta en ventas mostrador mostrar en pantalla una ventana el cual solicite el código de la tarjeta, con esto se validará si el código proporcionado coincide con el asignado anteriormente
 Después validar si el saldo del cliente es igual o mayor al monto especificado en la venta
 Si no es así, se cierra ventana del código y la venta no se guarda, si es favorable se procede a guardar la venta

**Comment by GhostX94** [comment]
Falta parte venta mostrador
